name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate language stats
        uses: readme-tools/readme-stats@v8
        with:
          card: languages
          options: username=ranjithkalai04-hub&layout=compact&hide_title=true
          path: dist/languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit stats
        uses: EndBug/add-and-commit@v9
        with:
          message: Update GitHub language stats
          add: "dist/languages.svg"